# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    displayName: 'Build and Test'
    jobs:
    - job: BuildAndTest
      displayName: 'Build, Test, Lint, and Coverage'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self

        - script: |
            python -m venv venv
            source venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          displayName: 'Setup Python environment'

        - script: |
            pip install flake8
            flake8
          displayName: 'Linting'

        - script: |
            pip install flask_sqlalchemy
            pip install pytest
            pytest tests/
          displayName: 'Run Tests'

        - script: |
            coverage run -m pytest 
            coverage report -m
            coverage xml
          displayName: 'Generate Code Coverage'

        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage.xml
          condition: succeededOrFailed()

