# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Lint
        displayName: 'Run Linting'
        steps:
          - script: |
              pip install -r requirements.txt
              flake8
        continueOnError: true

      - job: UnitTests
        displayName: 'Run Unit Tests'
        steps:
          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install --upgrade SQLAlchemy
              pytest tests/

      - job: CodeCoverage
        displayName: 'Run Code Coverage'
        steps:
          - script: |
              pip install -r requirements.txt
              coverage run -m pytest
              coverage report
            displayName: 'Run Code Coverage'
